// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package main

type TaxSimulation struct {
	TaxSimulationID          string
	Version                  int
	GrossSalary              int
	AhvBeitrag               int
	AlvBeitrag               int
	KtgBeitrag               int
	BvgBeitrag               int
	TaxableSalary            int
	Year                     int
	CommuneID                int
	Investment               int
	DeductionOther           int
	DeductionTransport       int
	DeductionProfession      int
	DeductionThirdPillar     int
	DeductionHealthInsurance int
	DeductionMeal            int
}
