// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package main

type LogTable struct {
	Msg         string
	Attributes  string
	LogLevel    int
	TimeString  string
	TimeUnix    int
	App         string
	Env         string
	CommitGit   string
	SrcFile     string
	SrcLine     int
	SrcFunction string
}
