// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: log_sqlite_queries.sql

package main

import (
	"context"
)

const writeLog = `-- name: WriteLog :exec
insert into log_table(
    msg, attributes, log_level, time_string, time_unix,
    app, env, commit_git, src_file, src_line, src_function
)
values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type WriteLogParams struct {
	Msg         string
	Attributes  string
	LogLevel    int
	TimeString  string
	TimeUnix    int
	App         string
	Env         string
	CommitGit   string
	SrcFile     string
	SrcLine     int
	SrcFunction string
}

func (q *Queries) WriteLog(ctx context.Context, arg WriteLogParams) error {
	_, err := q.db.ExecContext(ctx, writeLog,
		arg.Msg,
		arg.Attributes,
		arg.LogLevel,
		arg.TimeString,
		arg.TimeUnix,
		arg.App,
		arg.Env,
		arg.CommitGit,
		arg.SrcFile,
		arg.SrcLine,
		arg.SrcFunction,
	)
	return err
}
